# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
project_name: az-pim-cli

version: 2

before:
  hooks:
    - go mod tidy
builds:
  - binary: az-pim-cli
    ldflags: -s -w -X main.version={{ .Version }} -X main.commit={{ .ShortCommit }} -X main.date={{ .Date }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    wrap_in_directory: true
    name_template: '{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    files:
      - LICENSE
      - README.md

checksum:
  name_template: '{{ .ProjectName }}-{{ .Version }}-checksums.txt'

changelog:
  sort: asc
  groups:
    - title: 'Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: 'Documentation updates'
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 2
    - title: 'Other changes'
      order: 999

  filters:
    exclude:
      - "^.*test[(\\w)]*:"
      - "^.*ci[(\\w)]*:"
      - "^.*build[(\\w)]*:"
      - "Merge pull request"
      - "Merge branch"

release:
  github:
    owner: netr0m
    name: az-pim-cli

source:
  enabled: true
  name_template: '{{ .ProjectName }}-{{ .Version }}-source'
