name: 🐞 Bug Report
description: Report a bug to help us improve
labels: [bug]
body:
  - type: checkboxes
    id: terms
    attributes:
      label: Welcome
      options:
        - label: Yes, I've searched similar [issues on GitHub](https://github.com/netr0m/az-pim-cli/issues) and didn't find any.
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Description of the problem
      placeholder: Your problem description
    validations:
      required: true

  - type: textarea
    id: version
    attributes:
      label: Version of az-pim-cli
      value: |-
        <details>

        ```console
        $ az-pim-cli version
        # Paste output here
        ```

        </details>
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Configuration
      value: |-
        <details>

        ```console
        # provide the CLI flags you used when running your command here
        # make sure to sensor any confidential input
        ```

        </details>
    validations:
      required: true

  - type: textarea
    id: go-env
    attributes:
      label: Go environment
      value: |-
        <details>

        ```console
        $ go version && go env
        # paste output here
        ```

        </details>
    validations:
      required: true

  - type: textarea
    id: cmd-output
    attributes:
      label: Output of command
      value: |-
        <details>

        ```console
        # paste output here
        # make sure to sensor any confidential output
        ```

        </details>
    validations:
      required: true

  - type: checkboxes
    id: validation
    attributes:
      label: Validation
      options:
        - label: Yes, I've included all information above (version, config, etc.).
          required: true
