name: On Schedule
on:
  schedule:
    - cron: '30 2 * * 0'

permissions:
  contents: read
  security-events: write

jobs:
  snyk:
    name: Scan dependencies
    uses: ./.github/workflows/snyk.yaml
    with:
      severity-treshold: medium
    secrets: inherit

  semgrep:
    name: Scan source code
    uses: ./.github/workflows/semgrep.yaml
    secrets: inherit
