name: Run tests
on: [workflow_call]

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}-test

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          check-latest: true

      - name: Run go tests
        run: go test -v ./...
